### ISSUE TITLE
idToResolveMap's key value can be number but the request's id type is string.

### ISSUE THREAD

**Issue by jtsorg** [shogowada/json-rpc-2.0#51] opened 2023-12-02 15:09 UTC
In this case, it can't find the resolve function.

```typescript
responses.forEach((response) => {
      const resolve = this.idToResolveMap.get(response.id); <--- r**esponse.id is string but the idToResolveMap key value is number so it goes to else case. And then the request never return promise**
      if (resolve) {
        this.idToResolveMap.delete(response.id);
        resolve(response);
      }   
    });
```

Can you please check this bug please?

Thank you

**Comment by shogowada** [comment] 2023-12-02 21:04
Can you share the steps to reproduce?

**Comment by shogowada** [comment] 2023-12-03 13:35
OK, thanks for sharing how you set up the client side. How is the server side set up?

**Comment by shogowada** [comment] 2023-12-03 14:35
I see. If that's the case, it sounds like it's the server side converting the numeric ID to the string ID.

Can you try using the custom ID that uses a string ID? [The example is in the readme](https://github.com/shogowada/json-rpc-2.0#client-1), but something like this should do:
```typescript
let nextID: number = 0
const client = new JSONRPCClient(/* send function... */, () => String(nextID++))
```

**Comment by shogowada** [comment] 2023-12-14 15:20
Closing as this sounds like the problem is on the external server.

**Closed by shogowada** 2023-12-14 15:20 UTC
